companies/urls.py
from django.urls import path
from .views import *

app_name = 'companies'

urlpatterns = [
    path('', CompanyListView.as_view(), name='company-list'),
    path('<int:pk>/', CompanyDetailView.as_view(), name='company-detail'),
    path('<int:pk>/update/', CompanyUpdateView.as_view(), name='company-update'),
    path('<int:pk>/delete/', CompanyDeleteView.as_view(), name='company-delete'),
    path('create/', CompanyCreateView.as_view(), name='company-create'),
]

crm2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path, include
from users.views import LandingPageView, SignupView, SearchView, search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', include('users.urls', namespace="users")),
    path('products/', include('products.urls', namespace="products")),
    path('events/', include('events.urls', namespace="events")),
    path('companies/', include('companies.urls', namespace='companies')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('deals/', include('deals.urls', namespace="deals")),
    path('search/', search, name='search')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

companies/models.py
from django.db import models
from users.models import User

# Create your models here.


class Company(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=50, unique=True)
    phone = models.CharField(max_length=25, blank=True)
    website = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=250, blank=True)
    billing_street = models.CharField(max_length=50, blank=True)
    billing_city = models.CharField(max_length=50, blank=True)
    billing_state = models.CharField(max_length=50, blank=True)
    billing_country = models.CharField(max_length=50, blank=True)
    billing_code = models.CharField(max_length=20, blank=True)
    featured = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.company_name}'

companies/forms.py
from django import forms
from .models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field, Div


class CompanyModelForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = (
            'company_name',
            'phone',
            'website',
            'description',
            'billing_street',
            'billing_city',
            'billing_state',
            'billing_country',
            'billing_code',
            'featured',
        )
        help_texts = {
            'description': "This field will be visible in companies' list view."
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.label_class = 'block text-purple-700 text-sm font-bold mb-2'
        self.helper.layout = Layout(
            'company_name',
            'phone',
            'website',
            'description',
            'billing_street',
            'billing_city',
            'billing_state',
            'billing_country',
            'billing_code',
            'featured',
            Div(
                    Submit('submit', 'Submit', css_class="px-6 py-2 text-white bg-purple-500 border-0 rounded hover:bg-purple-600 text-center"), css_class='flex flex-col flex-wrap w-1/3 mx-auto mt-10'),
        )

companies/views.py
from django.shortcuts import render, redirect, reverse
from users.mixins import LoginRequiredMixin
from django.views import generic
from .models import Company
from .forms import CompanyModelForm

# Create your views here.


class CompanyListView(LoginRequiredMixin, generic.ListView):
    template_name = 'companies/company_list.html'
    context_object_name = 'companies'

    def get_queryset(self):
        active_user = self.request.user
        return Company.objects.filter(user=active_user, featured=False)

    def get_context_data(self, **kwargs):
        context = super(CompanyListView, self).get_context_data(**kwargs)
        queryset = Company.objects.filter(featured=True)
        context.update({
            'featured_companies': queryset
        })
        return context


class CompanyDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'companies/company_detail.html'
    context_object_name = 'company'

    def get_queryset(self):
        active_user = self.request.user
        return Company.objects.filter(user=active_user)


class CompanyCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'companies/company_create.html'
    form_class = CompanyModelForm

    def get_success_url(self):
        return reverse('companies:company-list')

    def form_valid(self, form):
        company = form.save(commit=False)
        company.user = self.request.user
        company.save()
        return super(CompanyCreateView, self).form_valid(form)


class CompanyUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'companies/company_update.html'
    form_class = CompanyModelForm

    def get_success_url(self):
        return reverse('companies:company-list')

    def get_queryset(self):
        active_user = self.request.user
        return Company.objects.filter(user=active_user)


class CompanyDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'companies/company_delete.html'

    def get_success_url(self):
        return reverse('companies:company-list')

    def get_queryset(self):
        active_user = self.request.user
        return Company.objects.filter(user=active_user)

companies/templates/companies/company_create.html
{% extends "base.html" %} {% load tailwind_filters %} {% load crispy_forms_tags %} {% block content %}

<section class="overflow-hidden text-gray-400 bg-gray-900 body-font min-h-screen max-h-full">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col flex-wrap mx-auto lg:w-4/5">
            <div class="max-w-full mx-auto mb-6 lg:w-1/2 lg:pr-10 lg:py-6 lg:mb-0">
                <div class="mb-10">
                    <a href="{% url 'companies:company-list' %}" class="px-6 py-2 text-white bg-purple-500 border-0 rounded hover:bg-purple-600 text-center">Go back to companies</a>
                </div>
                <h2 class="text-sm tracking-widest text-gray-500 title-font">COMPANY</h2>
                <h1 class="mb-4 text-3xl font-medium text-white title-font">Create new company</h1>
                <form method="post">
                    {% csrf_token %} {% crispy form %}
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

companies/templates/companies/company_delete.html
{% extends "base.html" %} {% block content %}

<section class="overflow-hidden text-gray-400 bg-gray-900 body-font min-h-screen max-h-full">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap mx-auto lg:w-4/5">
            <div class="w-full mb-6 lg:w-1/2 lg:pr-10 lg:py-6 lg:mb-0">
                <h2 class="text-sm tracking-widest text-gray-500 title-font">COMPANY</h2>
                <h1 class="mb-4 text-3xl font-medium text-white title-font">{{ company }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'companies:company-detail' company.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Details</a>
                    <a href="{% url 'companies:company-update' company.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Update</a>
                    <a class="flex-grow px-1 py-2 text-lg text-purple-400 border-b-2 border-purple-500">Delete</a>
                </div>
                <p class="mb-4 leading-relaxed">Are you sure you want to delete this company?</p>
                <p class="mb-4 leading-relaxed">This action cannot be reversed</p>
                <form method="post">
                    {% csrf_token %} {{ form.as_p }}
                    <button type="submit" class="flex px-6 py-2 ml-auto text-white bg-purple-500 border-0 rounded focus:outline-none hover:bg-purple-600">Delete</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

companies/templates/companies/company_detail.html
{% extends "base.html" %} {% block content %}

<section class="overflow-hidden text-gray-400 bg-gray-900 body-font min-h-screen max-h-full">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap mx-auto lg:w-4/5">
            <div class="w-full mb-6 lg:w-1/2 lg:pr-10 lg:py-6 lg:mb-0">
                <h2 class="text-sm tracking-widest text-gray-500 title-font">COMPANY</h2>
                <h1 class="mb-4 text-3xl font-medium text-white title-font">{{ company }}</h1>
                <div class="flex mb-4">
                    <a class="flex-grow px-1 py-2 text-lg text-purple-400 border-b-2 border-purple-500">Details</a>
                    <a href="{% url 'companies:company-update' company.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Update</a>
                    <a href="{% url 'companies:company-delete' company.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Delete</a>
                </div>
                <p class="mb-4 leading-relaxed">Company Information</p>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Phone</span>
                    <span class="ml-auto text-white">{{ company.phone }}</span>
                </div>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Website</span>
                    <span class="ml-auto text-white">{{ company.website }}</span>
                </div>
                <div class="flex py-2 mb-6 border-t border-b border-gray-800">
                    <span class="text-gray-500">Description</span>
                    <span class="ml-auto text-white">{{ company.description }}</span>
                </div>
                <p class="mb-4 leading-relaxed">Address Information</p>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Billing Street</span>
                    <span class="ml-auto text-white">{{ company.billing_street }}</span>
                </div>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Billing City</span>
                    <span class="ml-auto text-white">{{ company.billing_city }}</span>
                </div>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Billing State</span>
                    <span class="ml-auto text-white">{{ company.billing_state }}</span>
                </div>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Billing Country</span>
                    <span class="ml-auto text-white">{{ company.billing_country }}</span>
                </div>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Blling Code</span>
                    <span class="ml-auto text-white">{{ company.billing_code }}</span>
                </div>
                <div class="flex py-2 mb-6 border-t border-b border-gray-800">
                    <span class="text-gray-500">Featured</span>
                    <span class="ml-auto text-white">{{ company.featured }}</span>
                </div>
                <div class="flex">
                    <a href="{% url 'companies:company-list' %}" class="flex px-6 py-2 ml-auto text-white bg-purple-500 border-0 rounded focus:outline-none hover:bg-purple-600">Go back to companies</a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

companies/templates/companies/company_list.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-400 bg-gray-900 body-font min-h-screen max-h-full">
    <div class="container flex flex-wrap px-5 py-12 lg:py-24 mx-auto">
        <div class="flex flex-wrap w-full px-4 mb-4">
            <div class="flex flex-wrap flex-row w-full pb-4 border-b border-gray-700 items-end">
                <div class="w-1/3 text-left">
                    <a href="#" class="hover:text-purple-500"></a>
                </div>
                <div class="w-1/3 text-center">
                    <h2 class="mb-1 text-xs font-medium tracking-widest text-purple-400 title-font">COMPANIES</h2>
                    <h1 class="text-2xl font-medium text-white sm:text-3xl title-font">All of your companies</h1>
                </div>
                <div class="w-1/3 text-right">
                    <a href="{% url 'companies:company-create' %}" class="hover:text-purple-500">Create new company</a>
                </div>
            </div>
        </div>
        {% if featured_companies.exists %}
        <div class="flex flex-col w-full text-left p-4 md:w-1/3">
            <h2 class="mb-1 text-xl font-medium tracking-widest text-purple-400 title-font">FEATURED</h2>
        </div>
        <div class="flex flex-wrap w-full">
            {% for company in featured_companies%}
            <div class="p-4 md:w-1/3">
                <div class="flex flex-col h-full p-8 bg-gray-800 rounded-lg bg-opacity-60">
                    <div class="flex items-center mb-3">
                        <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 mr-3 text-white bg-purple-500 rounded-full">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M4 4a2 2 0 012-2h8a2 2 0 012 2v12a1 1 0 110 2h-3a1 1 0 01-1-1v-2a1 1 0 00-1-1H9a1 1 0 00-1 1v2a1 1 0 01-1 1H4a1 1 0 110-2V4zm3 1h2v2H7V5zm2 4H7v2h2V9zm2-4h2v2h-2V5zm2 4h-2v2h2V9z" clip-rule="evenodd" />
                            </svg>
                        </div>
                        <h2 class="text-lg font-medium text-white title-font">
                            {{ company }}
                        </h2>
                    </div>
                    <div class="flex-grow">
                        <p class="text-base leading-relaxed">
                            {% if company.description == '' %} No description provided for this company. {% else %} {{ company.description }} {% endif %}
                        </p>
                        <a href="{% url 'companies:company-detail' company.pk %}" class="inline-flex items-center mt-3 text-purple-400">
                            View this company
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <div class="flex flex-col w-full text-left p-4 md:w-1/3">
            <h2 class="mb-1 text-xl font-medium tracking-widest text-purple-400 title-font">ALL COMPANIES</h2>
        </div>
        <div class="flex flex-wrap w-full">
            {% for company in companies %}
            <div class="p-4 md:w-1/3">
                <div class="flex flex-col h-full p-8 bg-gray-800 rounded-lg bg-opacity-60">
                    <div class="flex items-center mb-3">
                        <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 mr-3 text-white bg-purple-500 rounded-full">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M4 4a2 2 0 012-2h8a2 2 0 012 2v12a1 1 0 110 2h-3a1 1 0 01-1-1v-2a1 1 0 00-1-1H9a1 1 0 00-1 1v2a1 1 0 01-1 1H4a1 1 0 110-2V4zm3 1h2v2H7V5zm2 4H7v2h2V9zm2-4h2v2h-2V5zm2 4h-2v2h2V9z" clip-rule="evenodd" />
                            </svg>
                        </div>
                        <h2 class="text-lg font-medium text-white title-font">
                            {{ company }}
                        </h2>
                    </div>
                    <div class="flex-grow">
                        <p class="text-base leading-relaxed">
                            {% if company.description == '' %} No description provided for this company. {% else %} {{ company.description }} {% endif %}
                        </p>
                        <a href="{% url 'companies:company-detail' company.pk %}" class="inline-flex items-center mt-3 text-purple-400">
                            View this company
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

companies/templates/companies/company_update.html
{% extends "base.html" %} {% load tailwind_filters %} {% load crispy_forms_tags %} {% block content %}

<section class="overflow-hidden text-gray-400 bg-gray-900 body-font min-h-screen max-h-full">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap mx-auto lg:w-4/5">
            <div class="w-full mb-6 lg:w-1/2 lg:pr-10 lg:py-6 lg:mb-0">
                <h2 class="text-sm tracking-widest text-gray-500 title-font">COMPANY</h2>
                <h1 class="mb-4 text-3xl font-medium text-white title-font">{{ company }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'companies:company-detail' company.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Details</a>
                    <a class="flex-grow px-1 py-2 text-lg text-purple-400 border-b-2 border-purple-500">Update</a>
                    <a href="{% url 'companies:company-delete' company.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Delete</a>
                </div>
                <form method="post">
                    {% csrf_token %} {% crispy form %}
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}