crm2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path, include
from users.views import LandingPageView, SignupView, SearchView, search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', include('users.urls', namespace="users")),
    path('products/', include('products.urls', namespace="products")),
    path('events/', include('events.urls', namespace="events")),
    path('companies/', include('companies.urls', namespace='companies')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('deals/', include('deals.urls', namespace="deals")),
    path('search/', search, name='search')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

deals/urls.py
from django.urls import path
from .views import *

app_name = "deals"

urlpatterns = [
    path('', DealListView.as_view(), name='deal-list'),
    path('<int:pk>/', DealDetailView.as_view(), name='deal-detail'),
    path('<int:pk>/update/', DealUpdateView.as_view(), name='deal-update'),
    path('<int:pk>/delete/', DealDeleteView.as_view(), name='deal-delete'),
    path('create/', DealCreateView.as_view(), name='deal-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
]

deals/models.py
from django.db import models
from users.models import User
from companies.models import Company
from contacts.models import Contact


# Create your models here.


class Deal(models.Model):

    UNCATEGORIZED = 'Uncategorized'
    CLASSIFICATION = 'Classification'
    SIZING = 'Sizing'
    QUOTATION = 'Quotation'
    NEGOTIATION = 'Negotiation'
    INVOICED = 'Invoiced'
    PAID_OUT = 'Paid Out'
    CLOSED_WON = 'Closed Won'
    CLOSED_LOST = 'Closed Lost'
    STAGE_CHOICES = [
        (UNCATEGORIZED, 'Uncategorized'),
        (CLASSIFICATION, 'Classification'),
        (SIZING, 'Sizing'),
        (QUOTATION, 'Quotation'),
        (NEGOTIATION, 'Negotiation'),
        (INVOICED, 'Invoiced'),
        (PAID_OUT, 'Paid Out'),
        (CLOSED_WON, 'Closed Won'),
        (CLOSED_LOST, 'Closed Lost')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    deal_name = models.CharField(max_length=50, unique=True)
    contact_name = models.ForeignKey(Contact, on_delete=models.CASCADE)
    company_name = models.ForeignKey(Company, on_delete=models.CASCADE)
    stage = models.CharField(
        max_length=20, choices=STAGE_CHOICES, default=UNCATEGORIZED)
    amount = models.FloatField(default=0)
    closing_date = models.DateField()
    description = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return f'{self.deal_name}'

deals/forms.py
from django import forms
from .models import Deal
from companies.models import Company
from contacts.models import Contact
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout, Submit, Div

Field.template = 'custom_fields/custom_field.html'


class DealModelForm(forms.ModelForm):
    class Meta:
        model = Deal
        fields = (
            'deal_name',
            'contact_name',
            'company_name',
            'stage',
            'amount',
            'closing_date',
            'description',
        )
        help_texts = {
            'description': "This field will be visible in deals' list view."
        }

    def __init__(self, *args, **kwargs):
        super(DealModelForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.label_class = 'block text-indigo-700 text-sm font-bold mb-2'
        self.helper.layout = Layout(
            'deal_name',
            'contact_name',
            'company_name',
            'stage',
            'amount',
            Field('closing_date', autocomplete='off'),
            'description',
            Div(
                    Submit('submit', 'Submit', css_class="px-6 py-2 text-white bg-indigo-500 border-0 rounded hover:bg-indigo-600 text-center"), css_class='flex flex-col flex-wrap w-1/3 mx-auto mt-10'),
        )

deals/views.py
from django.shortcuts import render, redirect, reverse
from users.mixins import LoginRequiredMixin, StaffAndLoginRequiredMixin
from django.views import generic
from .models import Deal
from .forms import DealModelForm

# Create your views here.


class DealListView(LoginRequiredMixin, generic.ListView):
    template_name = 'deals/deal_list.html'
    context_object_name = 'deals'

    def get_queryset(self):
        active_user = self.request.user
        return Deal.objects.filter(user=active_user)


class DealDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'deals/deal_detail.html'

    def get_queryset(self):
        active_user = self.request.user
        return Deal.objects.filter(user=active_user)


class DealCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "deals/deal_create.html"
    context_object_name = 'deals'
    form_class = DealModelForm

    def form_valid(self, form):
        deal = form.save(commit=False)
        deal.user = self.request.user
        deal.save()
        return super(DealCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse("deals:deal-list")


class DealUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "deals/deal_update.html"
    form_class = DealModelForm

    def get_queryset(self):
        active_user = self.request.user
        return Deal.objects.filter(user=active_user)

    def get_success_url(self):
        return reverse("deals:deal-list")


class DealDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = "deals/deal_delete.html"

    def get_success_url(self):
        return reverse("deals:deal-list")

    def get_queryset(self):
        active_user = self.request.user
        return Deal.objects.filter(user=active_user)


class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = 'deals/category_list.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        active_user = self.request.user
        queryset = Deal.objects.filter(user=active_user)

        uncategorized_deal_count = queryset.filter(
            stage=Deal.UNCATEGORIZED).count()
        classification_deal_count = queryset.filter(
            stage=Deal.CLASSIFICATION).count()
        sizing_deal_count = queryset.filter(stage=Deal.SIZING).count()
        quotation_deal_count = queryset.filter(
            stage=Deal.QUOTATION).count()
        negotiation_deal_count = queryset.filter(
            stage=Deal.NEGOTIATION).count()
        invoiced_deal_count = queryset.filter(
            stage=Deal.INVOICED).count()
        paid_out_deal_count = queryset.filter(
            stage=Deal.PAID_OUT).count()
        closed_won_deal_count = queryset.filter(
            stage=Deal.CLOSED_WON).count()
        closed_lost_deal_count = queryset.filter(
            stage=Deal.CLOSED_LOST).count()

        category_list = [
            Category('Uncategorized', uncategorized_deal_count),
            Category('Classification', classification_deal_count),
            Category('Sizing', sizing_deal_count),
            Category('Quotation', quotation_deal_count),
            Category('Negotiation', negotiation_deal_count),
            Category('Invoiced', invoiced_deal_count),
            Category('Paid Out', paid_out_deal_count),
            Category('Closed Won', closed_won_deal_count),
            Category('Closed Lost', closed_lost_deal_count),
        ]

        context.update({
            'category_list': category_list,
        })

        return context

    def get_queryset(self):
        active_user = self.request.user
        return Deal.objects.filter(user=active_user)


class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'deals/category_detail.html'
    context_object_name = 'name'

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        active_user = self.request.user
        queryset = Deal.objects.filter(user=active_user)

        uncategorized_deals = queryset.filter(stage=Deal.UNCATEGORIZED)
        classification_deals = queryset.filter(stage=Deal.CLASSIFICATION)
        sizing_deals = queryset.filter(stage=Deal.SIZING)
        quotation_deals = queryset.filter(stage=Deal.QUOTATION)
        negotiation_deals = queryset.filter(stage=Deal.NEGOTIATION)
        invoiced_deals = queryset.filter(stage=Deal.INVOICED)
        paid_out_deals = queryset.filter(stage=Deal.PAID_OUT)
        closed_won_deals = queryset.filter(stage=Deal.CLOSED_WON)
        closed_lost_deals = queryset.filter(stage=Deal.CLOSED_LOST)

        category_list = [
            ('Uncategorized', uncategorized_deals),
            ('Classification', classification_deals),
            ('Sizing', sizing_deals),
            ('Quotation', quotation_deals),
            ('Negotiation', negotiation_deals),
            ('Invoiced', invoiced_deals),
            ('Paid Out', paid_out_deals),
            ('Closed Won', closed_won_deals),
            ('Closed Lost', closed_lost_deals),
        ]

        context.update({
            'category_list': category_list,
        })
        return context

    def get_queryset(self):
        active_user = self.request.user
        return Deal.objects.filter(user=active_user)


class Category():

    def __init__(self, name: str, count: int):
        self.name = name
        self.count = count

deals/templates/deals/category_detail.html
{% extends "base.html" %} {% load tailwind_filters %} {% load crispy_forms_tags %} {% block content %}

<section class="text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-white">{{ name }}</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">All deals with a {{ name }} stage.</p>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm text-center bg-gray-800">Deal Name</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm text-center bg-gray-800">Closing Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in category_list %} {% if category == name %}
                    <tr>
                        <td class="px-4 py-3 text-center">{{ deal.deal_name }}</td>
                        <td class="px-4 py-3 text-center">{{ deal.closing_date }}</td>
                    </tr>
                    {% endif %} {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>

{% endblock content %}

deals/templates/deals/category_list.html
{% extends "base.html" %} {% load tailwind_filters %} {% load crispy_forms_tags %} {% block content %}

<section class="text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-white">Deal categories</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">All categories for deals</p>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm text-center bg-gray-800">Category</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm text-center bg-gray-800">Deal count</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in category_list %}
                    <tr>
                        <td class="px-4 py-3 text-center">{{ category.name }}</td>
                        <td class="px-4 py-3 text-center">{{ category.count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>

{% endblock content %}

deals/templates/deals/deal_create.html
{% extends "base.html" %} {% load tailwind_filters %} {% load crispy_forms_tags %} {% block content %}

<section class="overflow-hidden text-gray-400 bg-gray-900 body-font min-h-screen max-h-full">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap mx-auto lg:w-4/5">
            <div class="max-w-full mx-auto mb-6 lg:w-1/2 lg:pr-10 lg:py-6 lg:mb-0">
                <div class="mb-10">
                    <a href="{% url 'deals:deal-list' %}" class="px-6 py-2 text-white bg-indigo-500 border-0 rounded hover:bg-indigo-600 text-center">Go back to deals</a>
                </div>
                <h2 class="text-sm tracking-widest text-gray-500 title-font">DEAL</h2>
                <h1 class="mb-4 text-3xl font-medium text-white title-font">Create new deal</h1>
                <form method="post">
                    {% csrf_token %} {% crispy form %}
                </form>
            </div>
        </div>
    </div>
</section>
<script>
    $("input[name='closing_date']").datepicker({
        dateFormat: "yy-mm-dd"
    });
</script>
{% endblock content %}

deals/templates/deals/deal_delete.html
{% extends "base.html" %} {% block content %}

<section class="overflow-hidden text-gray-400 bg-gray-900 body-font min-h-screen max-h-full">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap mx-auto lg:w-4/5">
            <div class="w-full mb-6 lg:w-1/2 lg:pr-10 lg:py-6 lg:mb-0">
                <h2 class="text-sm tracking-widest text-gray-500 title-font">CONTACT</h2>
                <h1 class="mb-4 text-3xl font-medium text-white title-font">{{ deal }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'deals:deal-detail' deal.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Details</a>
                    <a href="{% url 'deals:deal-update' deal.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Update</a>
                    <a class="flex-grow px-1 py-2 text-lg text-indigo-400 border-b-2 border-indigo-500">Delete</a>
                </div>
                <p class="mb-4 leading-relaxed">Are you sure you want to delete this deal?</p>
                <p class="mb-4 leading-relaxed">This action cannot be reversed</p>
                <form method="post">
                    {% csrf_token %} {{ form }}
                    <button type="submit" class="flex px-6 py-2 ml-auto text-white bg-indigo-500 border-0 rounded focus:outline-none hover:bg-indigo-600">Delete</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

deals/templates/deals/deal_detail.html
{% extends "base.html" %} {% block content %}

<section class="overflow-hidden text-gray-400 bg-gray-900 body-font min-h-screen max-h-full">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap mx-auto lg:w-4/5">
            <div class="w-full mb-6 lg:w-1/2 lg:pr-10 lg:py-6 lg:mb-0">
                <h2 class="text-sm tracking-widest text-gray-500 title-font">DEAL</h2>
                <h1 class="mb-4 text-3xl font-medium text-white title-font">{{ deal }}</h1>
                <div class="flex mb-4">
                    <a class="flex-grow px-1 py-2 text-lg text-indigo-400 border-b-2 border-indigo-500">Details</a>
                    <a href="{% url 'deals:deal-update' deal.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Update</a>
                    <a href="{% url 'deals:deal-delete' deal.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Delete</a>
                </div>
                <p class="mb-4 leading-relaxed">Deal Information</p>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Contact Name</span>
                    <span class="ml-auto text-white">{{ deal.contact_name }}</span>
                </div>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Stage</span>
                    <span class="ml-auto text-white">TODO</span>
                </div>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Amount</span>
                    <span class="ml-auto text-white">{{ deal.amount }}</span>
                </div>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Closing Date</span>
                    <span class="ml-auto text-white">{{ deal.closing_date }}</span>
                </div>
                <div class="flex py-2 mb-6 border-t border-b border-gray-800">
                    <span class="text-gray-500">Description</span>
                    <span class="ml-auto text-white">{{ deal.description }}</span>
                </div>
                <div class="flex">
                    <a href="{% url 'deals:deal-list' %}" class="flex px-6 py-2 ml-auto text-white bg-indigo-500 border-0 rounded focus:outline-none hover:bg-indigo-600">Go back to deal</a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

deals/templates/deals/deal_list.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-400 bg-gray-900 body-font min-h-screen max-h-full">
    <div class="container flex flex-wrap px-5 py-12 lg:py-24 mx-auto">
        <div class="flex flex-wrap w-full px-4 mb-4">
            <div class="flex flex-wrap flex-row w-full pb-4 border-b border-gray-700 items-end">
                <div class="w-1/3 text-left">
                    <a href="{% url 'deals:category-list' %}" class="hover:text-indigo-500">View Categories</a>
                </div>
                <div class="w-1/3 text-center">
                    <h2 class="mb-1 text-xs font-medium tracking-widest text-indigo-400 title-font">DEALS</h2>
                    <h1 class="text-2xl font-medium text-white sm:text-3xl title-font">All of your deals</h1>
                </div>
                <div class="w-1/3 text-right">
                    <a href="{% url 'deals:deal-create' %}" class="hover:text-indigo-500">Create new deal</a>
                </div>
            </div>
        </div>
        <div class="flex flex-col w-full text-left p-4 md:w-1/3">
            <h2 class="mb-1 text-xl font-medium tracking-widest text-indigo-400 title-font">ALL DEALS</h2>
        </div>
        <div class="flex flex-wrap w-full">
            {% for deal in deals %}
            <div class="p-4 md:w-1/3">
                <div class="flex flex-col h-full p-8 bg-gray-800 rounded-lg bg-opacity-60">
                    <div class="flex items-center mb-3">
                        <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 mr-3 text-white bg-indigo-500 rounded-full">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M6 6V5a3 3 0 013-3h2a3 3 0 013 3v1h2a2 2 0 012 2v3.57A22.952 22.952 0 0110 13a22.95 22.95 0 01-8-1.43V8a2 2 0 012-2h2zm2-1a1 1 0 011-1h2a1 1 0 011 1v1H8V5zm1 5a1 1 0 011-1h.01a1 1 0 110 2H10a1 1 0 01-1-1z" clip-rule="evenodd" />
                                <path d="M2 13.692V16a2 2 0 002 2h12a2 2 0 002-2v-2.308A24.974 24.974 0 0110 15c-2.796 0-5.487-.46-8-1.308z" />
                            </svg>
                        </div>
                        <h2 class="text-lg font-medium text-white title-font">
                            {{ deal }}
                        </h2>
                    </div>
                    <div class="flex-grow">
                        <p class="text-base leading-relaxed">
                            {% if deal.description == '' %} No description provided for this deal. {% else %} {{ deal.description }} {% endif %}
                        </p>
                        <a href="{% url 'deals:deal-detail' deal.pk %}" class="inline-flex items-center mt-3 text-indigo-400">
                            View this deal
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

deals/templates/deals/deal_update.html
{% extends "base.html" %} {% load tailwind_filters %} {% load crispy_forms_tags %} {% block content %}

<section class="overflow-hidden text-gray-400 bg-gray-900 body-font min-h-screen max-h-full">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap mx-auto lg:w-4/5">
            <div class="w-full mb-6 lg:w-1/2 lg:pr-10 lg:py-6 lg:mb-0">
                <h2 class="text-sm tracking-widest text-gray-500 title-font">DEAL</h2>
                <h1 class="mb-4 text-3xl font-medium text-white title-font">{{ deal }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'deals:deal-detail' deal.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Details</a>
                    <a class="flex-grow px-1 py-2 text-lg text-indigo-400 border-b-2 border-indigo-500">Update</a>
                    <a href="{% url 'deals:deal-delete' deal.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Delete</a>
                </div>
                <form method="post">
                    {% csrf_token %} {% crispy form %}
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}