crm2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path, include
from users.views import LandingPageView, SignupView, SearchView, search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', include('users.urls', namespace="users")),
    path('products/', include('products.urls', namespace="products")),
    path('events/', include('events.urls', namespace="events")),
    path('companies/', include('companies.urls', namespace='companies')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('deals/', include('deals.urls', namespace="deals")),
    path('search/', search, name='search')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path('', UserListView.as_view(), name='user-list'),
    path('<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='user-delete'),
    path('create/', UserCreateView.as_view(), name='user-create'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    phone = models.CharField(max_length=25, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name} ({self.username})'

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field, Div

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',
                  'email',
                  'first_name',
                  'last_name',
                  'phone'
                  )
        field_classes = {'username': UsernameField}

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs = {'placeholder': 'Username'}
        self.fields['email'].widget.attrs = {'placeholder': 'example@mail.com'}
        self.fields['first_name'].widget.attrs = {'placeholder': 'First name'}
        self.fields['last_name'].widget.attrs = {'placeholder': 'Last name'}
        self.fields['phone'].widget.attrs = {'placeholder': 'Phone number'}
        self.helper = FormHelper()
        self.helper.label_class = 'block text-red-700 text-sm font-bold mb-2'
        self.helper.layout = Layout(
                'username',
                'email',
                'first_name',
                'last_name',
                'phone',
                'password',
                Div(
                    Submit('submit', 'Submit', css_class="px-6 py-2 text-white bg-red-500 border-0 rounded hover:bg-red-600 text-center"), css_class='flex flex-col flex-wrap w-1/3 mx-auto mt-10'),
        )

users/views.py
from django.shortcuts import render, redirect, reverse
from users.mixins import StaffAndLoginRequiredMixin
from django.views import generic
from .models import User
from .forms import CustomUserCreationForm
from companies.models import Company
from contacts.models import Contact
from deals.models import Deal
from events.models import Event
from products.models import Product
from tasks.models import Task


# Create your views here.


def search(request):
    if request.method == 'POST':
        search = request.POST.get('search')
        companies = Company.objects.filter(company_name__contains=search)
        contacts = Contact.objects.filter(first_name__contains=search)
        deals = Deal.objects.filter(deal_name__contains=search)
        events = Event.objects.filter(title__contains=search)
        products = Product.objects.filter(product_name__contains=search)
        tasks = Task.objects.filter(task_name__contains=search)

        context = {
            'search': search,
            'companies': companies,
            'contacts': contacts,
            'deals': deals,
            'events': events,
            'products': products,
            'tasks': tasks
        }

        return render(request, 'search.html', context)
    else:
        return render(request, 'search.html', {})


class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")


class LandingPageView(generic.TemplateView):
    template_name = "landing.html"


class SearchView(generic.TemplateView):
    template_name = "search.html"


class SecondPageView(generic.TemplateView):
    template_name = "second_page.html"


class UserListView(StaffAndLoginRequiredMixin, generic.ListView):
    template_name = "users/user_list.html"
    context_object_name = "users"

    def get_queryset(self):
        return User.objects.all()


class UserDetailView(StaffAndLoginRequiredMixin, generic.DetailView):
    template_name = "users/user_detail.html"
    context_object_name = "user"

    def get_queryset(self):
        return User.objects.all()


class UserCreateView(StaffAndLoginRequiredMixin, generic.CreateView):
    template_name = "users/user_create.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("users:user-list")


class UserUpdateView(StaffAndLoginRequiredMixin, generic.UpdateView):
    template_name = "users/user_update.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("users:user-list")

    def get_queryset(self):
        return User.objects.all()


class UserDeleteView(StaffAndLoginRequiredMixin, generic.DeleteView):
    template_name = "users/user_delete.html"

    def get_success_url(self):
        return reverse("users:user-list")

    def get_queryset(self):
        return User.objects.all()

users/templates/users/user_create.html
{% extends "base.html" %} {% load tailwind_filters %} {% load crispy_forms_tags %} {% block content %}

<section class="max-h-full min-h-screen overflow-hidden text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col flex-wrap mx-auto lg:w-4/5">
            <div class="max-w-full mx-auto mb-6 lg:w-1/2 lg:pr-10 lg:py-6 lg:mb-0">
                <div class="mb-10">
                    <a href="{% url 'users:user-list' %}" class="px-6 py-2 text-white bg-red-500 border-0 rounded hover:bg-red-600 text-center">Go back to users</a>
                </div>
                <h2 class="text-sm tracking-widest text-gray-500 title-font">USER</h2>
                <h1 class="mb-4 text-3xl font-medium text-white title-font">Create new user</h1>
                <form method="post">
                    {% csrf_token %} {% crispy form %}
                    <button type="submit" class="flex px-6 py-2 ml-auto text-white bg-red-500 border-0 rounded focus:outline-none hover:bg-red-600">Create user</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

users/templates/users/user_delete.html
{% extends "base.html" %} {% block content %}

<section class="max-h-full min-h-screen overflow-hidden text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap mx-auto lg:w-4/5">
            <div class="w-full mb-6 lg:w-1/2 lg:pr-10 lg:py-6 lg:mb-0">
                <h2 class="text-sm tracking-widest text-gray-500 title-font">USER</h2>
                <h1 class="mb-4 text-3xl font-medium text-white title-font">{{ user.first_name }} {{ user.last_name }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'users:user-detail' user.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Details</a>
                    <a href="{% url 'users:user-update' user.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Update</a>
                    <a class="flex-grow px-1 py-2 text-lg text-red-400 border-b-2 border-red-500">Delete</a>
                </div>
                <p class="mb-4 leading-relaxed">Are you sure you want to delete this user?</p>
                <p class="mb-4 leading-relaxed">This action cannot be reversed</p>
                <form method="post">
                    {% csrf_token %} {{ form.as_p }}
                    <button type="submit" class="flex px-6 py-2 ml-auto text-white bg-red-500 border-0 rounded focus:outline-none hover:bg-red-600">Delete</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

users/templates/users/user_detail.html
{% extends "base.html" %} {% block content %}

<section class="max-h-full min-h-screen overflow-hidden text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap mx-auto lg:w-4/5">
            <div class="w-full mb-6 lg:w-1/2 lg:pr-10 lg:py-6 lg:mb-0">
                <h2 class="text-sm tracking-widest text-gray-500 title-font">USER</h2>
                <h1 class="mb-4 text-3xl font-medium text-white title-font">{{ user.first_name }} {{ user.last_name }}</h1>
                <div class="flex mb-4">
                    <a class="flex-grow px-1 py-2 text-lg text-red-400 border-b-2 border-red-500">Details</a>
                    <a href="{% url 'users:user-update' user.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Update</a>
                    <a href="{% url 'users:user-delete' user.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Delete</a>
                </div>
                <p class="mb-4 leading-relaxed">Those are the details of this user.</p>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Mail</span>
                    <span class="ml-auto text-white">{{ user.mail }}</span>
                </div>
                <div class="flex py-2 border-t border-gray-800">
                    <span class="text-gray-500">Username</span>
                    <span class="ml-auto text-white">{{ user.username }}</span>
                </div>
                <div class="flex py-2 mb-6 border-t border-b border-gray-800">
                    <span class="text-gray-500">Phone</span>
                    <span class="ml-auto text-white">{{ user.phone }}</span>
                </div>
                <div class="flex">
                    <a href="{% url 'users:user-list' %}" class="flex px-6 py-2 ml-auto text-white bg-red-500 border-0 rounded focus:outline-none hover:bg-red-600">Go back to users</a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

users/templates/users/user_list.html
{% extends "base.html" %} {% block content %}

<section class="max-h-full min-h-screen text-gray-400 bg-gray-900 body-font">
    <div class="container flex flex-wrap px-5 py-24 mx-auto">
        <div class="flex flex-wrap w-full px-4 mb-4">
            <div class="flex flex-wrap flex-row w-full pb-4 border-b border-gray-700 items-end">
                <div class="w-1/3 text-left">
                </div>
                <div class="w-1/3 text-center">
                    <h2 class="mb-1 text-xs font-medium tracking-widest text-purple-400 title-font">USERS</h2>
                    <h1 class="text-2xl font-medium text-white sm:text-3xl title-font">All of your users</h1>
                </div>
                <div class="w-1/3 text-right">
                    <a href="{% url 'users:user-create' %}" class="hover:text-purple-500">Create new user</a>
                </div>
            </div>
        </div>
        <div class="flex flex-wrap w-full">
            {% for user in users %}
            <div class="p-4 md:w-1/3">
                <div class="flex flex-col h-full p-8 bg-gray-800 rounded-lg bg-opacity-60">
                    <div class="flex items-center mb-3">
                        <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 mr-3 text-white bg-indigo-500 rounded-full">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd" />
                            </svg>
                        </div>
                        <h2 class="text-lg font-medium text-white title-font">
                            {{ user.first_name }} {{ user.last_name}}
                        </h2>
                    </div>
                    <div class="flex-grow">
                        <p class="text-base leading-relaxed">
                            {% if user.username == '' %} No description provided for this user. {% else %} {{ user.username }} {% endif %}
                        </p>
                        <a href="{% url 'users:user-detail' user.pk %}" class="inline-flex items-center mt-3 text-indigo-400">
                            View this user
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

users/templates/users/user_update.html
{% extends "base.html" %} {% load tailwind_filters %} {% load crispy_forms_tags %} {% block content %}

<section class="max-h-full min-h-screen overflow-hidden text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap mx-auto lg:w-4/5">
            <div class="w-full mb-6 lg:w-1/2 lg:pr-10 lg:py-6 lg:mb-0">
                <h2 class="text-sm tracking-widest text-gray-500 title-font">USER</h2>
                <h1 class="mb-4 text-3xl font-medium text-white title-font">{{ user.first_name }} {{ user.last_name }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'users:user-detail' user.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Details</a>
                    <a class="flex-grow px-1 py-2 text-lg text-red-400 border-b-2 border-red-500">Update</a>
                    <a href="{% url 'users:user-delete' user.pk %}" class="flex-grow px-1 py-2 text-lg border-b-2 border-gray-800">Delete</a>
                </div>
                <form method="post">
                    {% csrf_token %} {% crispy form %}
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}