crm2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path, include
from users.views import LandingPageView, SignupView, SearchView, search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', include('users.urls', namespace="users")),
    path('products/', include('products.urls', namespace="products")),
    path('events/', include('events.urls', namespace="events")),
    path('companies/', include('companies.urls', namespace='companies')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('deals/', include('deals.urls', namespace="deals")),
    path('search/', search, name='search')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

deals/urls.py
from django.urls import path
from .views import *

app_name = "deals"

urlpatterns = [
    path('', DealListView.as_view(), name='deal-list'),
    path('<int:pk>/', DealDetailView.as_view(), name='deal-detail'),
    path('<int:pk>/update/', DealUpdateView.as_view(), name='deal-update'),
    path('<int:pk>/delete/', DealDeleteView.as_view(), name='deal-delete'),
    path('create/', DealCreateView.as_view(), name='deal-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
]

events/urls.py
from django.urls import path
from .views import *

app_name = "events"

urlpatterns = [
    path('', EventListView.as_view(), name='event-list'),
    path('<int:pk>/', EventDetailView.as_view(), name='event-detail'),
    path('<int:pk>/update/', EventUpdateView.as_view(), name='event-update'),
    path('<int:pk>/delete/', EventDeleteView.as_view(), name='event-delete'),
    path('create/', EventCreateView.as_view(), name='event-create'),
]

tasks/urls.py
from django.urls import path
from .views import *

app_name = 'tasks'

urlpatterns = [
    path('', TaskListView.as_view(), name='task-list'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('create/', TaskCreateView.as_view(), name='task-create'),
]

users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path('', UserListView.as_view(), name='user-list'),
    path('<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='user-delete'),
    path('create/', UserCreateView.as_view(), name='user-create'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
</head>

<body>
    {% include 'navbar.html' %} {% block content %} {% endblock content %} {% include 'footer.html' %} {% include "scripts.html" %}
</body>

</html>

templates/footer.html
<footer class="text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
        <a class="flex title-font font-medium items-center md:justify-start justify-center text-white">
            <span class="text-xl">CRM PRO</span>
        </a>
        <p class="text-sm text-gray-400 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-800 sm:py-2 sm:mt-0 mt-4">© 2021 CRM PRO —
            <a href="https://github.com/jmduro" class="text-gray-500 ml-1" target="_blank" rel="noopener noreferrer">@jmduro</a>
            and
            <a href="https://github.com/Alejojooo" class="text-gray-500 ml-1" target="_blank" rel="noopener noreferrer">@Alejojooo</a>
        </p>
        <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
        <a class="text-gray-400">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
            </svg>
        </a>
        <a class="ml-3 text-gray-400">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
            </svg>
        </a>
        <a class="ml-3 text-gray-400">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
            </svg>
        </a>
        <a class="ml-3 text-gray-400">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-discord w-5 h-5" viewBox="0 0 16 16">
                <path d="M13.545 2.907a13.227 13.227 0 0 0-3.257-1.011.05.05 0 0 0-.052.025c-.141.25-.297.577-.406.833a12.19 12.19 0 0 0-3.658 0 8.258 8.258 0 0 0-.412-.833.051.051 0 0 0-.052-.025c-1.125.194-2.22.534-3.257 1.011a.041.041 0 0 0-.021.018C.356 6.024-.213 9.047.066 12.032c.001.014.01.028.021.037a13.276 13.276 0 0 0 3.995 2.02.05.05 0 0 0 .056-.019c.308-.42.582-.863.818-1.329a.05.05 0 0 0-.01-.059.051.051 0 0 0-.018-.011 8.875 8.875 0 0 1-1.248-.595.05.05 0 0 1-.02-.066.051.051 0 0 1 .015-.019c.084-.063.168-.129.248-.195a.05.05 0 0 1 .051-.007c2.619 1.196 5.454 1.196 8.041 0a.052.052 0 0 1 .053.007c.08.066.164.132.248.195a.051.051 0 0 1-.004.085 8.254 8.254 0 0 1-1.249.594.05.05 0 0 0-.03.03.052.052 0 0 0 .003.041c.24.465.515.909.817 1.329a.05.05 0 0 0 .056.019 13.235 13.235 0 0 0 4.001-2.02.049.049 0 0 0 .021-.037c.334-3.451-.559-6.449-2.366-9.106a.034.034 0 0 0-.02-.019Zm-8.198 7.307c-.789 0-1.438-.724-1.438-1.612 0-.889.637-1.613 1.438-1.613.807 0 1.45.73 1.438 1.613 0 .888-.637 1.612-1.438 1.612Zm5.316 0c-.788 0-1.438-.724-1.438-1.612 0-.889.637-1.613 1.438-1.613.807 0 1.451.73 1.438 1.613 0 .888-.631 1.612-1.438 1.612Z"/>
            </svg>
        </a>
        <a class="ml-3 text-gray-400">
            <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
            <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
            <circle cx="4" cy="4" r="2" stroke="none"></circle>
            </svg>
        </a>
        </span>
    </div>
</footer>

templates/landing.html
{% extends "base.html" %} {% block content %}
<section class="max-h-full min-h-screen text-gray-400 bg-gray-900 body-font">
    <div class="container flex flex-col items-center justify-center px-5 py-24 mx-auto">
        <div class="w-full text-center lg:w-2/3">
            <h1 class="mb-4 text-3xl font-medium text-white title-font sm:text-4xl">
                CRM creado con Django
            </h1>
            <p class="mb-8 leading-relaxed">
                CRM PRO creado por los estudiantes universitarios Jorge Mario y Jorge Alejandro de la carrera de ingenieria en sistemas del CUNOR.
            </p>
        </div>
        <div style="position: relative; width: 50%; height: 0; padding-top: 50%;padding-bottom: 20px; margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden; border-radius: 2px;">
            <iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;" src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAEu6IMYKfg&#x2F;watch?embed">
            </iframe>
        </div>
    </div>
</section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-400 bg-gray-900 body-font">
    <div class="container flex flex-col flex-wrap items-center p-5 mx-auto lg:flex-row">
        <a href="{% url 'deals:deal-list' %}" class="flex items-center mb-4 font-medium text-white title-font lg:mb-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 p-2 text-white bg-indigo-500 rounded-full" viewBox="0 0 24 24">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
            <span class="ml-3 text-xl">CRM PRO</span>
        </a>
        <nav class="flex flex-wrap items-center justify-center text-base lg:mr-auto lg:ml-4 lg:py-1 lg:pl-4
        {% if request.user.is_authenticated %}
        lg:border-l lg:border-gray-700
        {% endif %}">
            {% if request.user.is_authenticated %}
            <a href="{% url 'deals:deal-list' %}" class="mr-5 hover:text-gray-50">Deals</a>
            <a href="{% url 'companies:company-list' %}" class="mr-5 hover:text-gray-50">Companies</a>
            <a href="{% url 'contacts:contact-list' %}" class="mr-5 hover:text-gray-50">Contacts</a>
            <a href="{% url 'products:product-list' %}" class="mr-5 hover:text-gray-50">Products</a>
            <a href="{% url 'tasks:task-list' %}" class="mr-5 hover:text-gray-50">Tasks</a>
            <a href="{% url 'events:event-list' %}" class="mr-5 hover:text-gray-50">Events</a> {% if request.user.is_superuser %}
            <a href="{% url 'users:user-list' %}" class="mr-5 hover:text-gray-50">Users</a> {% endif %} {% endif %}
        </nav>
        {% if request.user.is_authenticated %}
        <div class="pt-2 relative text-gray-600">
            <form action="{% url 'search' %}" method="post">
                {% csrf_token %}
                <input method="post" action="{% url 'search' %}" class="border-2 border-gray-300 bg-white h-10 px-5 pr-16 rounded-lg text-sm focus:outline-none" type="search" name="search" placeholder="Search">
                <button type="submit" class="absolute right-0 top-0 mt-5 mr-4">
                  <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
                    viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
                    width="512px" height="512px">
                    <path
                      d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
                  </svg>
                </button>
            </form>
        </div>
        <span class="inline-flex items-center px-3 py-1 mt-4 text-base border-0 rounded lg:mt-0">
            Welcome, {{ request.user.first_name }} {{ request.user.last_name }}
        </span>
        <a href="{% url 'logout' %}" class="inline-flex items-center px-3 py-1 mt-4 text-base bg-gray-800 border-0 rounded focus:outline-none hover:bg-gray-700 lg:mt-0">
            Logout
            <svg fill="none" xmlns="http://www.w3.org/2000/svg" stroke="currentColor" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
            </svg>
        </a> {% else %}
        <a href="{% url 'signup' %}" class="inline-flex items-center px-3 py-1 mt-4 text-base border-0 rounded hover:text-indigo-500 md:mt-0">
            Sign Up
        </a>
        <a href="{% url 'login' %}" class="inline-flex items-center px-3 py-1 mt-4 text-base bg-gray-800 border-0 rounded focus:outline-none hover:bg-gray-700 md:mt-0">
            Login
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </a> {% endif %}
    </div>
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>

templates/search.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-400 bg-gray-900 body-font overflow-hidden min-h-screen max-h-full">
    <div class="container px-5 py-24 mx-auto">
        {% if search %}
        <h1 class="text-2xl font-medium text-white sm:text-3xl title-font mb-8">You searched for {{ search }}</h1>
        {% else %}
        <h1 class="text-2xl font-medium text-white sm:text-3xl title-font mb-8">You forgot to search for something! Try again</h1>
        {% endif %}
        <div class="-my-8 divide-y-2 divide-gray-800">
            {% for company in companies %}
            <div class="py-8 flex flex-wrap md:flex-nowrap">
                <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                    <span class="font-semibold title-font text-white">COMPANY</span>
                    <span class="mt-1 text-gray-500 text-sm">
                        {% if company.featured %}
                        Featured
                        {% else %}
                        All companies
                        {% endif %}
                    </span>
                </div>
                <div class="md:flex-grow">
                    <h2 class="text-2xl font-medium text-white title-font mb-2">{{ company }}</h2>
                    <p class="leading-relaxed">
                        {% if company.description != '' %} {{ company.description }} {% else %} No description provided for this company. {% endif %}
                    </p>
                    <a href="{% url 'companies:company-detail' company.pk %}" class="text-purple-400 inline-flex items-center mt-4">View this company
                        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path d="M5 12h14"></path>
                            <path d="M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="flex border-b-1 border-gray-800 flex-wrap md:flex-nowrap"></div>
            {% endfor %} {% for contact in contacts %}
            <div class="py-8 flex flex-wrap md:flex-nowrap">
                <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                    <span class="font-semibold title-font text-white">CONTACT</span>
                    <span class="mt-1 text-gray-500 text-sm">
                        {% if contact.featured %}
                        Featured
                        {% else %}
                        All contacts
                        {% endif %}
                    </span>
                </div>
                <div class="md:flex-grow">
                    <h2 class="text-2xl font-medium text-white title-font mb-2">{{ contact }}</h2>
                    <p class="leading-relaxed">
                        {% if contact.description != '' %} {{ contact.description }} {% else %} No description provided for this contact. {% endif %}
                    </p>
                    <a href="{% url 'contacts:contact-detail' contact.pk %}" class="text-red-400 inline-flex items-center mt-4">View this contact
                        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path d="M5 12h14"></path>
                            <path d="M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="flex border-b-1 border-gray-800 flex-wrap md:flex-nowrap"></div>
            {% endfor %} {% for deal in deals %}
            <div class="py-8 flex flex-wrap md:flex-nowrap">
                <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                    <span class="font-semibold title-font text-white">DEAL</span>
                    <span class="mt-1 text-gray-500 text-sm">
                        TODO
                    </span>
                </div>
                <div class="md:flex-grow">
                    <h2 class="text-2xl font-medium text-white title-font mb-2">{{ deal }}</h2>
                    <p class="leading-relaxed">
                        {% if deal.description != '' %} {{ deal.description }} {% else %} No description provided for this deal. {% endif %}
                    </p>
                    <a href="{% url 'deals:deal-detail' deal.pk %}" class="text-indigo-400 inline-flex items-center mt-4">View this deal
                        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path d="M5 12h14"></path>
                            <path d="M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="flex border-b-1 border-gray-800 flex-wrap md:flex-nowrap"></div>
            {% endfor %} {% for event in events %}
            <div class="py-8 flex flex-wrap md:flex-nowrap">
                <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                    <span class="font-semibold title-font text-white">EVENT</span>
                    <span class="mt-1 text-gray-500 text-sm">{{ event.date_from }} to {{ event.date_to }}</span>
                </div>
                <div class="md:flex-grow">
                    <h2 class="text-2xl font-medium text-white title-font mb-2">{{ event }}</h2>
                    <p class="leading-relaxed">
                        {% if event.description != '' %} {{ event.description }} {% else %} No description provided for this event. {% endif %}
                    </p>
                    <a href="{% url 'events:event-detail' event.pk %}" class="text-pink-400 inline-flex items-center mt-4">View this event
                        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path d="M5 12h14"></path>
                            <path d="M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="flex border-b-1 border-gray-800 flex-wrap md:flex-nowrap"></div>
            {% endfor %} {% for product in products %}
            <div class="py-8 flex flex-wrap md:flex-nowrap">
                <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                    <span class="font-semibold title-font text-white">PRODUCT</span>
                    <span class="mt-1 text-gray-500 text-sm">
                        {% if product_active %}
                        Active
                        {% else %}
                        Inactive
                        {% endif %}
                    </span>
                </div>
                <div class="md:flex-grow">
                    <h2 class="text-2xl font-medium text-white title-font mb-2">{{ product }}</h2>
                    <p class="leading-relaxed">
                        {% if product.description != '' %} {{ product.description }} {% else %} No description provided for this product. {% endif %}
                    </p>
                    <a href="{% url 'products:product-detail' product.pk %}" class="text-green-400 inline-flex items-center mt-4">View this product
                        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path d="M5 12h14"></path>
                            <path d="M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="flex border-b-1 border-gray-800 flex-wrap md:flex-nowrap"></div>
            {% endfor %} {% for task in tasks %}
            <div class="py-8 flex flex-wrap md:flex-nowrap">
                <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                    <span class="font-semibold title-font text-white">TASK</span>
                    <span class="mt-1 text-gray-500 text-sm">{{ task.due_date }}</span>
                </div>
                <div class="md:flex-grow">
                    <h2 class="text-2xl font-medium text-white title-font mb-2">{{ task }}</h2>
                    <p class="leading-relaxed">
                        {% if task.description != '' %} {{ task.description }} {% else %} No description provided for this task. {% endif %}
                    </p>
                    <a href="{% url 'tasks:task-detail' task.pk %}" class="text-blue-400 inline-flex items-center mt-4">View this task
                        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path d="M5 12h14"></path>
                            <path d="M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="flex border-b-1 border-gray-800 flex-wrap md:flex-nowrap"></div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

templates/second_page.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

</head>

<body>
    <header class="text-gray-400 bg-gray-900 body-font">
        <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
            <a class="flex title-font font-medium items-center text-white mb-4 md:mb-0">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
                <span class="ml-3 text-xl">CRM PRO</span>
            </a>
            <a href="{% url 'signup' %}" class="inline-flex items-center px-3 py-1 mt-4 text-base border-0 rounded hover:text-green-700 md:mt-0">
                Sign Up
            </a>
            <a href="{% url 'login' %}" class="inline-flex items-center px-3 py-1 mt-4 text-base bg-gray-800 border-0 rounded focus:outline-none hover:bg-gray-700 md:mt-0">
                Login
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
            </a>
        </div>
    </header>

    <section class="text-gray-400 bg-gray-900 body-font">
        <div class="container flex flex-col items-center justify-center px-5 py-24 mx-auto">
            <img class="object-cover object-center w-5/6 mb-10 rounded lg:w-2/6 md:w-3/6" alt="hero" src="https://dummyimage.com/720x600">
            <div class="w-full text-center lg:w-2/3">
                <h1 class="mb-4 text-3xl font-medium text-white title-font sm:text-4xl">
                    CRM creado con Django Second
                </h1>
                <p class="mb-8 leading-relaxed">
                    Esto es otra prueba para los users
                </p>
                <div class="flex justify-center">
                    <button class="inline-flex px-6 py-2 text-lg text-white bg-indigo-500 border-0 rounded focus:outline-none hover:bg-indigo-600">
                        Button
                    </button>
                    <button class="inline-flex px-6 py-2 ml-4 text-lg text-gray-400 bg-gray-800 border-0 rounded focus:outline-none hover:bg-gray-700 hover:text-white">
                        Button
                    </button>
                </div>
            </div>
        </div>
    </section>
</body>

</html>